CREATE TABLE IF NOT EXISTS movies (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title VARCHAR(255) NOT NULL,
    year INTEGER NOT NULL,
    runtime INTEGER NOT NULL,
    genres JSON NOT NULL,
    version INTEGER NOT NULL DEFAULT 1
);
